### ISSUE TITLE
Ajax without Pjax?

### ISSUE THREAD

**Issue by siliconalchemy** [kartik-v/yii2-editable#100]
Hi

Like others I'm struggling to get editable working within content loaded through ajax.  I don't want to/can't  use pjax.  This is a great general interface plugin but a bit limited if it doesn't work with vanilla jquery/ajax.

Is there some sample code or a pointer in the right direction?

**Comment by kartik-v** [comment]
Techincally its possible for ajax as well. You as the developer needs to write the necessary JS code to initialize the plugin after you have overwritten the HTML markup via AJAX (that will break the jquery bindings). In some cases (depending on your design) using yii's renderAjax method to overwrite the HTML can help as the widget will try to reinitialize itself.

**Comment by kartik-v** [comment]
An enhancement has been provided - you can use the plugin's `destroy` and `create` methods via enhancement #87. Also an `initEditablePopover` method has been provided where you can pass the toggleButton reference id to initialize popover after ajax replace.

**Comment by nadirvishun** [comment]
@kartik-v 
Thanks for this widget.
I have the same question in ajax load without pjax。
assume  `id` is unique id like `status-1` or something 
```
  $("#"+id+"-cont").editable("destroy").editable("create");
  initEditablePopover("#"+id+"-targ");
```
but I should initable the options，assume the option object is `editable_a690100c` ,it's value like:
```
window.editable_eaca81be = {"valueIfNull":"not set","asPopover":true,"placement":"left","target":".kv-editable-link","displayValueConfig":[],"ajaxSettings":[],"showAjaxErrors":true,"submitOnEnter":true,"selectAllOnEdit":true,"encodeOutput":true,"closeOnBlur":false,"validationDelay":500,"resetDelay":200,"animationDelay":300};
```
so ,I should add this for init:
```
$("#"+id+"-cont").editable(editable_a690100c)
```
but how can get the hash `a690100c`? in some other widget like switchinput ,we can get the hash like this:
```
var opts = window[$("#"+id).attr("data-krajee-bootstrapSwitch")];
$("#"+id).bootstrapSwitch(opts);
```
but in editable widget ,I can not get the hash
please help me how to resolve this prombles
