### ISSUE TITLE
Hide validation error when press enter key

### ISSUE THREAD

**Issue by jekaspekas** [kartik-v/yii2-editable#101]
Hi Kartik.
I am having a problem with submit on enter.
When validation error return (['output'=>'', 'message'=>'Validation error']), input is hiding instead display an error.
This result only when press enter key.
P.S. Sorry for my english

**Comment by kartik-v** [comment]
Cannot exactly reproduce this. Check if you have updated release from dev-master.

If you have a case you can reproduce please share and will reopen this issue.
