### ISSUE TITLE
submitButton style issue

### ISSUE THREAD

**Issue by gprepok** [kartik-v/yii2-editable#102]
Hi Kartik!

I noticed that the submitButton default icon is:
```php
$submitIcon = ArrayHelper::remove($submitOpts, 'icon', '<i class="glyphicon glyphicon-save"></i>');
```
from the source.
According to the documentation http://demos.krajee.com/editable#settings that should be:
```html
<i class="glyphicon glyphicon-ok"></i> 
```
If I modify it by hand to the glyphicon-ok, then the style dies:
![image](https://cloud.githubusercontent.com/assets/11618106/11762099/fdea9578-a0db-11e5-94b1-cad7bdd7eea8.png)

Regards

**Comment by kartik-v** [comment]
You are supposed to set this in `submitButton` property of Editable widget as mentioned in docs

```
'submitButton' => ['icon' => '<i class="glyphicon glyphicon-ok"></i> ']
```

**Comment by gprepok** [comment]
Thanks for the answer. From one side this is my mistake; my problem is on the EditableColumn and not in the normal Editable widget.
But on the other hand, If i set what you suggested, then I get the problem I described above.
```php
'headerOptions' => ['style'=>'text-align:center', 'class'=>'kv-align-middle'],
  'class' => 'kartik\grid\EditableColumn',
  'attribute' => my_attribute,
  'editableOptions' => [
    'submitButton' => ['icon' => '<i class="glyphicon glyphicon-ok"></i> '],  
    ...
  ]
]
```
