### ISSUE TITLE
Editable column not showing validation error

### ISSUE THREAD

**Issue by jamesepi** [kartik-v/yii2-editable#106]
Hi,

I set up a gridview with an editable column and when i try to save it the model->save() returns false due to validation errors, but it isn't shown in the popover.

In the controller, the code for the editable is:

        // validate if there is a editable input saved via AJAX
        if (Yii::$app->request->post('hasEditable')) {
            // instantiate the model for saving
            $model_id = Yii::$app->request->post('editableKey');
            $model = MyModel::findOne($model_id);

            // store a default json response as desired by editable
            $out = Json::encode(['output' => '', 'message' => '']);
            
            $posted = current($_POST['MyModel']);
            $post = ['MyModel' => $posted];

            // load model like any single model validation
            if ($model->load($post)) {
                
                // can save model or do something before saving model
                $success = $model->save(); //if false, should display error in the popover, but it's not doing that.
                                
                $output = '';
                             
                $out = Json::encode(['output' => $output, 'message' => '']);                
            }
            // return ajax json encoded response and exit
            echo $out;
            return;
        }

The only way i could make it show the error was like this:

            // load model like any single model validation
            if ($model->load($post)) {
                
                // can save model or do something before saving model
                $success = $model->save();
                $errors = $model->errors;
                
                $output = '';
                $message = '';
                
                if (!$succes) {                    
                    foreach ($errors as $error) {
                        $message .= $error[0];
                    }
                }
               
                $out = Json::encode(['output' => $output, 'message' => $message]);                
            }

In the code above i set the message for the output manually, according to $model->errors

The gridview has the column set like this:
[
            'attribute' => 'name',
            'class' => 'kartik\grid\EditableColumn',
            'pageSummary' => true,
],

It also has pjax set to true.

Best regards,

**Comment by kartik-v** [comment]
It will only show an error if you send the message key with the json output. You need to decide as the developer what error you wish to show and set it in message.

Note though that model rules that use yii client validation via yii active field will automatically display the related validation errors.

**Comment by jamesepi** [comment]
Yes, that's what i'm trying to get, the validation errors from the rules. In this case it's a required rule.

Somehow i'm not being able to see it, so i tried to process manually.

It showed ok, but i didn't want to do that because i understand the rules should be automatic.

I'm trying to figure out why. I'm missing something, but don't know what.

Thank you for your reply
