### ISSUE TITLE
Editable not working in GridView

### ISSUE THREAD

**Issue by unNene** [kartik-v/yii2-editable#109]
Hi,

I have this column in GridView:
  ```
   [
            'class' => 'kartik\grid\EditableColumn',
            'attribute'=>'status',
            'editableOptions' => [
                'header' => 'Statut',
                'inputType' => Editable::INPUT_DROPDOWN_LIST,
                'data' => \yii\helpers\ArrayHelper::map(Yii::$app->params['comandaStatus'],'status','status'),
            ],
            'hAlign'=>'right',
            'vAlign'=>'middle',
            'width'=>'100px',
            'pageSummary' => true
    ],
```

In page it looks like Editable:
![image](https://cloud.githubusercontent.com/assets/900974/13026768/a5c269d8-d23c-11e5-8cab-dba7af6a1f4d.png)

But when I click on this column nothing happens. I tried to use @dev version, stable version, also I tried with dev version for all components - is not working.

Everything worked fine until I did an update, after that I can find the problem.
In browser console I don't see any JS errors. 
In HTML code I have the JS code for editable generated.

**Comment by kartik-v** [comment]
Sorry cannot reproduce your use case. You may need to check your code.

**Comment by CtrlShiftN** [comment]
I even do not show anything! It appears like normal text. How can I fix it?
