### ISSUE TITLE
Not post anything inside Activeform

### ISSUE THREAD

**Issue by izemize** [kartik-v/yii2-editable#114]
Hi!

When i use this widget in ActiveForm, not sending anything... when button clicked (not submitButton). Ajax not sending any data to controller, and request is GET, not POST.

```php
<?php
$this->beginBlock('szemelyes');
$form = ActiveForm::begin([
	'id'=>'szemelyes',
	'method'=>'POST',
	//'options'=>['enctype'=>'multipart/form-data']
]); ?>
<div class="col-lg-12">
	<div class="row">
		<div class="col-lg-8">
			<?=$form->field($teacher,'details')->widget(Editable::className(),[
				'asPopover'=>false,
				'inputType'=>Editable::INPUT_TEXTAREA,
				'options'=>[
					'class'=>'form-control',
					'rows'=>5,
					'style'=>'width:400px',
				],
			]);?>
		</div>
	</div>
	<div class="row">
		<div class='pull-right' style="margin-top:10px;margin-right: 10px;">
			<?= Html::submitButton('Mentés',['class'=>'btn btn-segitunk']); ?>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<?php ActiveForm::end(); ?>
<?php $this->endBlock(); ?>
```

**Comment by yanhuixie** [comment]
We may run into the same problem. I guess it might be because the nested form and submit behavior. It looks like outer form is submitted via ajax GET, but not the one generated by EditableColumn.

**Comment by yanhuixie** [comment]
#86

**Comment by kartik-v** [comment]
As mentioned in the [other comment](https://github.com/kartik-v/yii2-grid/issues/471#issuecomment-211910357) rethink your design and DO NOT render NESTED HTML forms. 

Nested HTML Forms will be treated as bad invalid HTML by browsers and will break your web app code.
