### ISSUE TITLE
Several fields

### ISSUE THREAD

**Issue by andreybuzin** [kartik-v/yii2-editable#115]
Hello.
I need to display several fields after clicking one cell in GridView. How I can get it?
I see, I can use 'beforeInput' and 'afterInput' for rendering fields . But I don't understand how it helps me. 

I need smth like this:
```
'inputType' => function ($form) use ($editableModel) {
    return
    $form->field($editableModel, 'country')->textInput(['placeholder'=>'Country']) . "\n" .
    $form->field($editableModel, 'street')->textInput(['placeholder'=>'Street']) . "\n" .
    $form->field($editableModel, 'building')->textInput(['placeholder'=>'Building']) . "\n";
}
```
![image](https://cloud.githubusercontent.com/assets/3225101/13976037/ad367514-f0f6-11e5-84e4-2cf9cec5497b.png)

**Comment by andreybuzin** [comment]
Now I'm using 'inputType'=>Editable::INPUT_HIDDEN and 'beforeInput' section for my fields. I'd like to find a more elegant solution

**Comment by kartik-v** [comment]
Editable is generally intended to edit the value of displayed content (not a generic button that launches a modal form).

You need to therefore code this for your use case using `beforeInput` or `afterInput`. An example of multiple fields is [provided in the demo (look at the address example)](http://demos.krajee.com/editable) -- it uses `afterInput` in the example.
