### ISSUE TITLE
bootstrap-popover-x invalid after node switched when using with yii2-tree-manager

### ISSUE THREAD

**Issue by yanhuixie** [kartik-v/yii2-editable#118]
Let's consider about the layout bellow:
<img width="1191" alt="2016-04-21 11 10 27" src="https://cloud.githubusercontent.com/assets/1049615/14697016/d5d52394-07b2-11e6-855a-c0517774890f.png">

The first time whole page rendered and select a tree node, Editable function is normal (bootstrap-popover-x popup). since the selection of another tree node, or switch back to the first selected tree node, Editable function is invalid (bootstrap-popover-x can't popup). There is no exception/error in backend app and browser console. No matter the 'enableCache' option of yii2-tree-manager is true or false.

Any suggestion is appreciated. Thank you!

**Comment by kartik-v** [comment]
It is more to do with your code. Your use case is ajax based rendering and hence any JS / JQUERY plugins will need to be reinitialized after the markup is overwritten by ajax.
