### ISSUE TITLE
Unserialize don't work in controller with composite keys

### ISSUE THREAD

**Issue by ipppinto** [kartik-v/yii2-editable#122]
Hi,

First, thank you for or work.

I have a problem with editableKey and composite keys.

In my controller I have this:

```
            $post1 = Yii::$app->request->post();
            
            print_r($post1);
            
            echo $post1['editableKey'];
            
            $var1 = unserialize($post1['editableKey']);  

            echo $var1['carrinho_id'].'->test1';
            echo $var1['produto_id'].'->test2';
```

And in debug I have this

Array ( [_csrf] => WTFpTVFxVnAecC99EyYiPht7Oi8SFT5JdF8DBygeezsRXxouHkUvHQ== [hasEditable] => 1 [editableIndex] => 0 [editableKey] => {"carrinho_id":10,"produto_id":3292} [editableAttribute] => quantidade [CarrinhoProduto] => Array ( [0] => Array ( [quantidade] => 24 ) ) ) {"carrinho_id":10,"produto_id":3292}->test1->test2

I don't know why unserialize($post1['editableKey']) don't work. I have something wrong?

**Comment by ipppinto** [comment]
The solution:

$var1 = Json::decode(Yii::$app->request->post('editableKey'));

**Comment by kartik-v** [comment]
Yes composite key is stored as JSON.
