### ISSUE TITLE
yii2-gridview  Failed to set the 'value' property on 'HTMLInputElement'

### ISSUE THREAD

**Issue by manks0127** [kartik-v/yii2-editable#123]
in yii2 gridview,
`[
                'attribute' => 'image_url',
                'value' => 'image_url',
                'class'=>'kartik\grid\EditableColumn',
                'editableOptions'=>[
                    'inputType'=>\kartik\editable\Editable::INPUT_FILE,
                ],
],`
jquery.js:7617 Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

**Comment by patmir** [comment]
This issue still persist while using Editable::INPUT_FILE or EDITABLE:INPUT_FILEINPUT widget for EditableColumn in DynaGrid:

`  [
                    'class'=>'kartik\grid\EditableColumn',
                    'attribute' => 'icon',
                    'editableOptions' => function ($model, $key, $index){
                        return [
                            'header' => Yii::t('app', 'Ikona'),
                            'inputType' => Editable::INPUT_FILE,
                            'format' => Editable::FORMAT_BUTTON,
                            'formOptions' => [
                                'options'=>[
                                        'enctype'=>'multipart/form-data',
                                ]
                            ],
                            'options' => [
                                'options' => [
                                    'accept' => 'image/*',
                                ],
                                'pluginOptions' => [
                                    'showUpload' => false,
                                    'overwriteInitial'=>true,
                                    'initialPreview' => [$model->icon],
                                    'initialPreviewAsData'=>true,
                                ]
                            ],
                        ];
                    },
                ],`

When clicking on submit button it produced following error:

Uncaught DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
