### ISSUE TITLE
Inline mode widget hiding before error shown (on Enter press only)

### ISSUE THREAD

**Issue by wa1kb0y** [kartik-v/yii2-editable#128]
If you press Enter, widget disappearing immediately, on inline mode only. If an error occurred, it can only be seen if you click on widget again. But clicking on submit button works correctly. I'm not strong in js and not found how to fix. Thank you for the great widget!

**Comment by kartik-v** [comment]
Set `Editable::submitOnEnter` property to `false` for your use case above to prevent submit on enter keypress.

**Comment by wa1kb0y** [comment]
But i need to submit on Enter keypress :) If set `submitOnEnter` to `false` input just hiding anyway.

**Comment by wa1kb0y** [comment]
This is my widget code

```
<?php
echo Editable::widget([
    'ajaxSettings'=>['url' => Url::to(['blablabla/update'])],
    'asPopover' => false,
    'buttonsTemplate'=>'{submit}',
    'submitButton' =>['icon'=>'<i class="glyphicon glyphicon-ok"></i>'],
    'format' => Editable::FORMAT_BUTTON,
    'name' => 'address',
    'value' => $address,
    'header' => 'Address',
    'size' => 'md',
    'options' => ['class'=>'form-control', 'placeholder'=>'Enter address...']
]);
?>
```

**Comment by kartik-v** [comment]
Will need to check on this when I get time and update. Opening this.

**Comment by gb5256** [comment]
I can confirm this issue. 
Experiencing the same behaviour.
