### ISSUE TITLE
problem with editable+select2

### ISSUE THREAD

**Issue by soju7** [kartik-v/yii2-editable#130]
working on editable+select2 .Values that enter into the multiselect is saving fine .But those db values don't persist once we click the edit button after refreshing the page. here is my code.
 <?php echo Editable::widget([
                                    'name' => $title,
                                    'asPopover' => false,  
                                    'header' => '',
                                    'size' => 'md',
                                    'inputType' => Editable::INPUT_SELECT2,
                                    'format' => Editable::FORMAT_BUTTON,
                                    'options' => [
                                        'showToggleAll' => false,
                                        'data' => $item_option, 'class' => 'form-control NW hint-out',
                                        'value' => $intern_data_value,
                                        'options' => [
                                            'placeholder' => 'Limit selections to those that contain this text',
                                            'multiple' => true,
                                            'class' => 'hint-out',
                                            'data-maxlength' => $item_maxlength
                                        ],
                                        'pluginOptions' => [
                                            'width' => 500,
                                            'tags' => true,
                                            'closeOnSelect' => false,
                                            'maximumSelectionLength' => $item_maxlength,
                                        ],
                                    ],
                                    'editableButtonOptions' => [
                                        'label' => '<i class="fa fa-pencil"></i>',
                                        'class' => 'editbuttonclass',
                                    ],
                                    'buttonsTemplate' => '{submit}',
                                    'submitButton' => [
                                        'icon' => '<i class="fa fa-floppy-o"></i>',
                                        'class' => 'btn btn-sm btn-primary',
                                        'label' => Yii::t('app', 'Save')
                                    ],
                                ]);
?>
where $intern_data_value are comma separated values. 
thanks in advance.

**Comment by n8b** [comment]
Where is $intern_data_value being read from the db?

**Comment by soju7** [comment]
'apple','orange','banana' like so
