### ISSUE TITLE
The message file for category 'kvselect' does not exist

### ISSUE THREAD

**Issue by oteixido** [kartik-v/yii2-editable#138]
The message file for category 'kvselect' does not exist: vendor/kartik-v/yii2-widget-select2/messages/ca/kvselect.php

**Comment by kartik-v** [comment]
Please submit a Pull request for your language in this repo.

**Comment by oteixido** [comment]
Oriol.teixido@gmail.com

**Comment by oteixido** [comment]
Oriol.teixido@upc.edu
