### ISSUE TITLE
editable is not working in every row in expandable grid 

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-editable#144]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-editable.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/editable).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Using editable widget inside kartik expandable grid 
2.
3.

## Expected behavior and actual behavior
buttons with editable value should open,but only first table row button is opening on click,
When I follow those steps, I see...
editable widget in grid inside expandable grid.
I was expecting...
it should open in all table rows,but only one row button is opening.other row divs and button id is same in every row.
![error-1](https://cloud.githubusercontent.com/assets/8582472/21961174/a91b3ab0-db28-11e6-8227-924178352eb6.png)
![error-2](https://cloud.githubusercontent.com/assets/8582472/21961173/a91a65f4-db28-11e6-92f6-e60c8746735e.png)

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ *] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-editable version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/editable)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-editable without other plugins.

**Comment by kartik-v** [comment]
its obvious... you must have unique identifiers for each editable widget... else the plugin will fail to initialize because of invalid HTML (due to duplicate identifiers).

**Comment by ajkosh** [comment]
dont mind but it is lack of documentations ,i cant see anywhere how to set id of div you are generating from render html and button id.that is not related to your widget id .i have unique identifiers for widgets.but your html is rendering same id.Please correct yourself first.

**Comment by ajkosh** [comment]
I tell you same and simple thing use simple html table and keep one button with same id  in every row.it will work in only in one row not to all rows.so there is only one thing you are wrong or you dnt want to resolve or lack of documentation.

**Comment by kartik-v** [comment]
To clarify again, It has nothing to do with the Expanded row markup or its div identifiers... but depends on how you are programming to render the Editable content and the widget.

If you have multiple Editable widgets (assuming that expand row is rendered without ajax) - then the `options['id']` for each and every editable widget must be unique.

If you are doing the above with ajax... then you need to take care of the plugin init after expand row is clicked (there is some level of automation and integration provided with PJAX based reinitialization for these widgets)

**Comment by kartik-v** [comment]
To clarify again, It has nothing to do with the Expanded row markup or its div identifiers... but depends on how you are programming to render the Editable content and the widget.

If you have multiple Editable widgets (assuming that expand row is rendered without ajax) - then the `options['id']` for each and every editable widget rendered in every row must be unique. This is true for all Yii 2 input widgets mostly - which initialize the jquery plugins based on `options['id']`.

If you are doing the above with ajax... then you need to take care of the plugin init after expand row is clicked and the same rule applies there as well (ID must be unique).

Also for ajax rendering cases, the jquery plugin may need to be reinitialized after the markup is rendered (there is some level of automation and integration provided with PJAX based reinitialization for these widgets however).

**Comment by kartik-v** [comment]
> I tell you same and simple thing use simple html table and keep one button with same id  in every row.it will work in only in one row not to all rows.

Exactly what I was saying earlier - this is basics of HTML markup and elements with DUPLICATE ID is treated as invalid HTML...  You should not allow HTML elements and markup with duplicate IDs to be rendered on your page.

**Comment by ajkosh** [comment]
I did same as you said.i am not using any pjax now.i found problem is div id and button Id same as attribute name.so in every row of table it is creating same I'd for button which is using to open popover.i am big fan of ur widgets.Please can u send issue 133 .I think it is similar.

**Comment by kartik-v** [comment]
You need to use the table row key or something to generate a unique ID for each Editable widget in every row. For example the `ExpandRowColumn` has the `detail` property which can be set as a Closure as well.. you get the `$key` and `$index`... use that to generate an unique Editable widget `options['id']`.

**Comment by ajkosh** [comment]
Ok I got it.i try this .
Thank you very much.

**Comment by ajkosh** [comment]
i did same as you told and used all index and key option but button id is same every time
below is button id creating from different records of table.
[code]<button type="button" id="toursettings-0-capacity-targ" class="btn btn-sm btn-default kv-editable-button kv-editable-toggle"><i class="glyphicon glyphicon-pencil"></i></button>[/code]
and second record button id is 
[code]<button type="button" id="toursettings-0-capacity-targ" class="btn btn-sm btn-default kv-editable-button kv-editable-toggle"><i class="glyphicon glyphicon-pencil"></i></button>[/code]

if i m using popover true then it is working fine but 2nd row record popover is coming top of page

**Comment by FedericoBenedetti1976** [comment]
> i did same as you told and used all index and key option but button id is same every time below is button id creating from different records .
> 
> ```
> <button type="button" id="toursettings-0-capacity-targ" class="btn btn-sm btn-default kv-editable-button kv-editable-toggle"><i class="glyphicon glyphicon-pencil"></i></button>
> ```
> 
> and second record button id is
> 
> ```
> <button type="button" id="toursettings-0-capacity-targ" class="btn btn-sm btn-default kv-editable-button kv-editable-toggle"><i class="glyphicon glyphicon-pencil"></i></button>
> ```
> 
> if i m using popover true then it is working fine but 2nd row record popover is coming top of page

Hi, do you solve this problem? I have same issue with popover coming top of page. Thank's
