### ISSUE TITLE
kartik-v/yii2-editable with yiidoc/yii2-redactor together, is it possible?

### ISSUE THREAD

**Issue by baldiri** [kartik-v/yii2-editable#154]
Hi,

as the title says, can i use them together? in which way? 

Thanks in advance!

**Comment by kartik-v** [comment]
Do not know about the extension mentioned... but it should be possible to use any other widget based on `yii\widgets\InputWidget`.

You need to set `Editable::inputType` property to `Editable::INPUT_WIDGET` and go ahead with setting the `Editable::widgetClass` to the classname of your custom widget and then set the widget options within `Editable::options`.
