### ISSUE TITLE
no option to setup popover container

### ISSUE THREAD

**Issue by maxlyaptsev** [kartik-v/yii2-editable#155]
I have editable widget inside sidebar with scroll, so sidebar scrolls together with popover. I need to place popover inside sidebar continer. To do this I need to change option in bootstrap-popover-x.js

**Comment by maxlyaptsev** [comment]
temporary fix
`
   $('#container').on('scroll', function (e) {
        ScrollTop = $('#container').scrollTop();
        if(typeof popoverTopInit == "undefined")
        {
            popoverTopInit = $('.popover-x-body >  .kv-editable-popover').offset().top;
        }

        $('.popover-x-body > .kv-editable-popover').offset({'top' : (popoverTopInit - ScrollTop)});

    });
`

**Comment by farhadno** [comment]
> 
> 
> temporary fix
> 
> ```
>    $('#container').on('scroll', function (e) {
>         ScrollTop = $('#container').scrollTop();
>         if(typeof popoverTopInit == "undefined")
>         {
>             popoverTopInit = $('.popover-x-body >  .kv-editable-popover').offset().top;
>         }
>         $('.popover-x-body > .kv-editable-popover').offset({'top' : (popoverTopInit - ScrollTop)});
>     });
> ```

i'm try this but not working
