### ISSUE TITLE
Clicking Enter on text input submit the form to main form as well

### ISSUE THREAD

**Issue by manojkumar1412** [kartik-v/yii2-editable#158]
Hi Kartik,

I am using editable widget which has url set to other action than main form action. Now, when editable text input opens inline and i press enter, it submits the form to main url rather than url set in formOptions. However, clicking on apply button works well. But, It is very intuitive to press enter to change the value.

Also, is it possible to avoid ajax call, if i don't want to do any processing on server side?

Thanks
Manoj

**Comment by kartik-v** [comment]
You cannot embed the editable widget (which has its own form) in another HTML form. It will render your HTML markup invalid - because you would be NESTING forms which is not supported in HTML.
