### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by crissty** [kartik-v/yii2-editable#168]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-editable.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/editable).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Use kartik\grid\EditableColumn in yii2-grid
2. Used together with inputType property with value Editable::INPUT_SPIN
3. Execute "$.pjax.reload" of yii2-grid pjax container

## Expected behavior and actual behavior

When I follow those steps, I get the next error:

> TypeError: Cannot read property 'getBoundingClientRect' of undefined

Error in file: js/bootstrap-popover-x.min.js, in line:

```
getPosition: function () {`
           var self = this, $el = self.$target, elRect = $el[0].getBoundingClientRect(), $container = self.$body, cssPos = $container.css('position');
           ...
}
```

This provoke that Javascript code not working after of this. Also, this error does not always happen, only sometimes without difference in execution

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

**Comment by yaroslavolekh** [comment]
I have same the issue

**Comment by seraos** [comment]
I have the same issue
