### ISSUE TITLE
ajax load  dynamic content can not reinitialize the options

### ISSUE THREAD

**Issue by nadirvishun** [kartik-v/yii2-editable#175]
## the problem

I used the Editable widget without Grid and pjax，when ajax load dynamic content, this content has editable field，so I should reinitialize it:
assume  `id` is unique id like `status-1` or something 
```
  $("#"+id+"-cont").editable("destroy").editable("create");//inite the event
  initEditablePopover("#"+id+"-targ");//inite the propver
```
but I also should initable the options，assume the option object is `editable_a690100c` ,it's value like:
```
window.editable_eaca81be = {"valueIfNull":"not set","asPopover":true,"placement":"left","target":".kv-editable-link","displayValueConfig":[],"ajaxSettings":[],"showAjaxErrors":true,"submitOnEnter":true,"selectAllOnEdit":true,"encodeOutput":true,"closeOnBlur":false,"validationDelay":500,"resetDelay":200,"animationDelay":300};
```
so ,I should add this for init:
```
$("#"+id+"-cont").editable(editable_a690100c)
```
but how can get the hash `a690100c`? 
in some other widget like `switchinput` ,we can get the hash like this:
```
var opts = window[$("#"+id).attr("data-krajee-bootstrapSwitch")];
$("#"+id).bootstrapSwitch(opts);
```
but in editable widget ,I can not get the hash.

## how to resolve it

---
maybe ,we should add this code in `Editable.php` in function `initEditable`:
```
...
 Config::validateInputWidget($this->inputType);
        $this->initI18N(__DIR__);
        $this->initOptions();
        $this->_popoverOptions['options']['id'] = $this->options['id'] . '-popover';
        $this->_popoverOptions['toggleButton']['id'] = $this->options['id'] . '-targ';
        $this->registerAssets();

        //add this line in below
        $this->_popoverOptions['toggleButton']['data-krajee-editable'] = $this->options['data-krajee-editable'];

        echo Html::beginTag('div', $this->containerOptions);
        if ($this->format == self::FORMAT_BUTTON) {
            echo Html::tag('div', $this->displayValue, $this->editableValueOptions);
        }
...
``` 
is there any other method to resolve it?

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:v3.2.1
- yii2-editable version:Version 1.7.6

**Comment by strtob** [comment]
Hi,

I had the same problem, here is my solution for you:

$.ajax({
                url: '/url-action',
                type: 'GET',
                dataType: 'html',
                success: function(data) {
                    $('#main').html(data);
                    
                    // init editable column
                    $('.kv-editable-link').each(function(index) {
                        initEditablePopover($(this).attr('id'));
                    });
                                   
                }
            });
