### ISSUE TITLE
Uncaught TypeError: e.replace is not a function

### ISSUE THREAD

**Issue by Danielesk** [kartik-v/yii2-editable#177]
view
![image](https://user-images.githubusercontent.com/10652829/43769905-6e535a88-9a6d-11e8-92a3-e396c782dfc9.png)

controller
![image](https://user-images.githubusercontent.com/10652829/43770878-27ca556e-9a70-11e8-8664-e9a2753f419f.png)

result

![image](https://user-images.githubusercontent.com/10652829/43769960-9207a6be-9a6d-11e8-85d9-e0a8ff9ddff8.png)

What is the cause? I checked the information or there is no solution.

**Comment by Danielesk** [comment]
Your demo just shows the configuration in the view, but there are no controllers and models, so the effect is too big for your official website.

**Comment by kartik-v** [comment]
Get the latest code. Fixed via [the latest commit](https://github.com/kartik-v/yii2-editable/commit/e4116792b80c04eb39347dc1cc712eb43fb5381d)
