### ISSUE TITLE
ActiveForm not required in composer

### ISSUE THREAD

**Issue by gorets** [kartik-v/yii2-editable#182]
Exception 'yii\base\InvalidConfigException' with message 'The form class '\kartik\form\ActiveForm' does not exist.

**Comment by YuriVL** [comment]
Need to install kartik-v/yii2-widget-activeform
$ php composer.phar require kartik-v/yii2-widget-activeform "dev-master" 
Or add: "kartik-v/yii2-widget-activeform": "dev-master" to your application's composer.json file
