### ISSUE TITLE
Getting unknown property: app\models\UserSession::car.car_id

### ISSUE THREAD

**Issue by daniroyo** [kartik-v/yii2-editable#185]
When I try to use a related attribute, it doesn´t work.
Work correctly with stable GridView Yii2 Core

## Steps to reproduce the issue

1. I use car.car_id as attribute and it fails.

My model architecture is like that:

UserSession 1 -----> 1 Car

```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: app\models\UserSession::car.car_id
```

Just before changing GridView Component, it worked ok.

There is the needed function to reference car as attribute os UserSession.

```
    public function getCar()
    {
        return $this->hasOne(Car::className(), ['car_id' => 'car_id']);
    }
```

#### Browsers

-  Safari

#### Operating System

-  Mac OS X

**Comment by kartik-v** [comment]
You need to set the grid column attributes in array format and return dependent / related values using closure if you are using with EditableColumn.

**Comment by daniroyo** [comment]
Thank you @kartik-v , I am not sure of understanding correctly, but I will see later.

Great extension!
