### ISSUE TITLE
Editable has css conflict with adminLTE 3

### ISSUE THREAD

**Issue by ZiyaVakhobov** [kartik-v/yii2-editable#190]
When using editable with admin lte 3 theme. The modal is not closing and dispalying before clicking. here is link how is it looking. https://ibb.co/b76GcFb

**Comment by umid206uz** [comment]
'assetManager' => [
            'bundles' => [
                'yii\bootstrap4\BootstrapAsset' => [
                    'sourcePath' => '@vendor/almasaeed2010/adminlte/dist',
                    'css'=>[
                        'css/adminlte.min.css'
                    ]
                ],
            ],
        ],

**Comment by umid206uz** [comment]
`'assetManager' => [
            'bundles' => [
                'yii\bootstrap4\BootstrapAsset' => [
                    'sourcePath' => '@vendor/almasaeed2010/adminlte/dist',
                    'css'=>[
                        'css/adminlte.min.css'
                    ]
                ],
            ],
        ],`

**Comment by DeveloperdotAbuzar** [comment]
> When using editable with admin lte 3 theme. The modal is not closing and dispalying before clicking. here is link how is it looking. https://ibb.co/b76GcFb

> 

Brother,

If someone is using Hail812 AdminLTE3 extension, it has prerequisite almasaeed2010.
to resolve this issue, go to:
     vendor\almasaeed2010\adminlte\dist\css\adminlte.min.css
Look for the css class ".popover" and remove this "display:block" in this class.
