### ISSUE TITLE
(Bootstrap 4 issues) Editable Popover popped-up by itself in wrong position upon loading, popover window won't close after succesful editing the field, Inline not working etc 

### ISSUE THREAD

**Issue by codeneet** [kartik-v/yii2-editable#191]
Hi, I'm using this widget with bootstrap 4. I had set `'bsVersion'=>'4'` property in Editable.php and also setup the bsVersion property within Yii 2 application params as per documentation. I had several issues :
1. Editable PopOver popped-up by itself on the top-left  corner every time the page is refreshed/loaded. If you have more than one editable popOver in one page, only one window automatically appear upon page loading. In my screenshot, the one with "second" value is the auto-popped one. Can't be close. It will only close and reappear on the correct position after I click the "second" button (use screenshot as reference. It's the one that trigger the PopOver )
2. After succesful editing the value/content of the popOver field, it won't automaticaly close.
3. The editable-fields are in a button-like appearance 
![Homes](https://user-images.githubusercontent.com/47771923/57196367-78882580-6f86-11e9-90e4-1d9359b42a16.png)

3. Inline version not working. Oddly my default seems to be set to the popOver version, even when i set  `'asPopover'=>'false',` it still didn't work, nothing happen when I try to trigger with clicking it as if it isn't an editable field at all. 

4. I've followed the documentation of the ajax processing section, but the value after succesful input will only change on the view after page refresh. The value is saved to the database 'tho; only the view won't change its value directly as in normal Ajax processing.

 My view file :
```
   echo Editable::widget([
    'model' => $model, 
    'attribute' => 'tema',
    'value'=>$model->tema,
/*'asPopover'=>'false',*/
    'type' => 'post',
    'header'=>'tema', 
    'valueIfNull'=>'value-nya NULL',
    'format'=>'link',
    'size'=> 'lg',
    'inputType' => Editable::INPUT_TEXT,
    'editableValueOptions' => ['class' => 'text-success h3'],
    'options'=>['class' => 'panel panel-default'],
]);        
```
The controller
```
// table only has one row
$model= Home::find()->one();

    /*// Check if there is an Editable ajax request
    if (isset($_POST['hasEditable'])) {

        // use Yii's response format to encode output as JSON
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        // read your posted model attributes
        if ($model->load($_POST)) {
            // read or convert your posted information. 
            $value = $model->tema;
           $model->save();
            // return JSON encoded output in the below format
            return ['output'=>$value, 'message'=>'success!'];
            // alternatively you can return a validation error
            // return ['output'=>'', 'message'=>'Validation error'];
        }
        // else if nothing to do always return an empty JSON encoded output
        else {
            return ['output'=>'', 'message'=>'fail'];
        }
```

**Comment by MattiCerio** [comment]
I have the same problem

**Comment by MattiCerio** [comment]
Solved by setting the parameter `'bsDependencyEnabled' => true` in `config/params.php`  !
