### ISSUE TITLE
how to handle this error , i cant save the multivalue , only show loading

### ISSUE THREAD

**Issue by ramdan123** [kartik-v/yii2-editable#199]
![image](https://user-images.githubusercontent.com/29086757/73816597-9d623f80-481b-11ea-8541-2cbfb0df3603.png)

my view

![image](https://user-images.githubusercontent.com/29086757/73816616-ac48f200-481b-11ea-8e9d-89effa90e310.png)

my controller 

![image](https://user-images.githubusercontent.com/29086757/73816627-b539c380-481b-11ea-96f8-7612b6b79555.png)

![image](https://user-images.githubusercontent.com/29086757/73816681-d7cbdc80-481b-11ea-8691-f53ff683bbc8.png)

**Comment by AlanHeckinJohnston** [comment]
This is because of a server error, fix the error on your server.
