### ISSUE TITLE
Editable events list after first page

### ISSUE THREAD

**Issue by SplendornetTech** [kartik-v/yii2-editable#201]
Hi,
First off all, thank you for the all hard work you have putin to make yii2 grid and other widgets useful.
I am using Kartik-editable grid with it's own pjax event like below

GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax' => true,
            'pager' => [
                'class' => \kop\y2sp\ScrollPager::className(),
                'container' => '.grid-view tbody',
                'item' => 'tr',
                'paginationSelector' => '.grid-view .pagination',
                'triggerTemplate' => '<tr class="ias-trigger"><td colspan="100%" style="text-align: left"><a style="cursor: pointer">{text}</a></td></tr>',
                'eventOnRendered' => 'function() {showColumns();}',
            ],
                        [
                    'class' => 'kartik\grid\EditableColumn',
                    'header' => 'Delivery Date',
                    'attribute' => 'delivery_date',
                    'format' => 'html',
                    'value' => function ($data) {
                        if (!empty($data->tempOaDetails) && $data->is_temp) {
                            return ($data->tempOaDetails->delivery_date=='0000-00-00')? '' : date("d-m-Y", strtotime($data->tempOaDetails->delivery_date));
                        } else {
                            $OaDetails = app\models\OaDetails::find()->where(['oa_key' => $data->oa_key])->one();
                            return ($OaDetails->delivery_date=='0000-00-00')? '' : date("d-m-Y", strtotime($OaDetails->delivery_date));
                        }
                    },
                    'headerOptions' => ['class' => 'setWidth delivery_date', 'style' => 'color:#3c8dbc;text-align:left;'],
                    'contentOptions' => ['class' => 'delivery_date', 'style' => 'text-align:left'],
                    'editableOptions' => function ($data) use ($accessLevel,$action, $sales_target_year){
                        if(($accessLevel::checkAccess('Add Order Acceptance') && 
                            $action != 'oa-revision-index' && 
                            \app\models\TempOaType::getSalesTargetYear20() == $sales_target_year || 
                            User::isAdminUser())){
                            $date = '';
                            if (!empty($data->tempOaDetails) && $data->is_temp) {
                                $date =  ($data->tempOaDetails->delivery_date=='0000-00-00')? '' : date("d-m-Y", strtotime($data->tempOaDetails->delivery_date));
                            } else {
                                $OaDetails = app\models\OaDetails::find()->where(['oa_key' => $data->oa_key])->one();
                                $date = ($OaDetails->delivery_date=='0000-00-00')? '' : date("d-m-Y", strtotime($OaDetails->delivery_date));
                            }
                            $date = Helper::convertDateTimeInView($date);
                            $date= ($date == '0000-00-00' || $date == '') ? date('d-m-yy') : $date;
                            return [
                                'name'=>'Delivery Date', 
                                'asPopover' => true,
                                'header' => 'Specify/Change Delivery Date',
                                'attribute' => 'delivery_date',
                                'size'=>'ms',
                                'inputType' => Editable::INPUT_DATE,
                                'value' => $date,
                                'options'=>[
                                    'options'=>['placeholder'=>'Select Date','value'=>$date,'data-key'=>$data->oa_key],
                                    'pluginOptions' => [
                                        'autoclose'=>true,
                                        'format' => 'dd-mm-yyyy'
                                    ]
                                ],
                                'editableValueOptions' => [ 'disabled' => $data->oa_main_status != 'Completed' ? false : true],
                            ];
                        } else return;
                    }
                ], 
I am also using "https://github.com/kop/yii2-scroll-pager" to acheive infinite loading. For the initial default rows this combination works as expected. When I try to load more rows from the infitnite loader option, the events on the editable column cells are gone. How can I rebind those either through my code or any events available on the grid column?

Any help or directions would be hightly appreciated.

Regards
Aditya

**Comment by kartik-v** [comment]
Since the editable widget uses its own internal jQuery plugins - if you are overwriting content by your custom javascript - you need to reinitalize the plugins via your own javascript code after you have rendered them - need to check the code of Editable Widget and check how the plugin is reinitialized... it may not be that straightforward. 

Alternatively try to render dynamic content by PJAX in the grid's pjax container - the widget auto reintializes if you have embedded content dynamically within the same pjax container.

**Comment by kartik-v** [comment]
Alternatively - an enhancement can be included in this GRID extension to include Scroll Pager as an additional functionality - this would need help from others. Am open to it.

**Comment by SplendornetTech** [comment]
> Alternatively - an enhancement can be included in this GRID extension to include Scroll Pager as an additional functionality - this would need help from others. Am open to it.

Yes this would be great to have. Let me first get over this issue and then I will see how both can be combined. Thank you for your response.

**Comment by SplendornetTech** [comment]
> Since the editable widget uses its own internal jQuery plugins - if you are overwriting content by your custom javascript - you need to reinitalize the plugins via your own javascript code after you have rendered them. It may not be that straightforward -- you need to check the code of Editable Widget CLASS and check how the plugin is reinitialized... and reinitialize it via javascript with the right identifiers after your third party javascript plugin has rendered the content (you need to tap into the third party plugin's events).
> 
> Alternatively try to render dynamic content by PJAX in the grid's pjax container - the widget auto reintializes if you have embedded content dynamically within the same pjax container.

I am not sure I understood the last part, sorry to ask you, but can you please help me with example?

**Comment by kartik-v** [comment]
The yii2-grid extension already includes two properties  in the `GridView` class i.e. `pjax` and `pjaxSettings` . Check docs.

If `pjax` is set to `true` - the extension creates a pjax container identifier based on `pjaxSettings` and the default activities like `pagination` and `filtering` are done via PJAX rendered content. In that case the jquery plugins used as part of GridView like `EditableColumn` are auto initialized

You can try to render dynamic content via PJAX in the same container and when you trigger pjax container reload the krajee plugins rendered inside will auto initialize.

**Comment by SplendornetTech** [comment]
> The yii2-grid extension already includes two properties in the `GridView` class i.e. `pjax` and `pjaxSettings` . Check docs.
> 
> If `pjax` is set to `true` - the extension creates a pjax container identifier based on `pjaxSettings` and the default activities like `pagination` and `filtering` are done via PJAX rendered content. In that case the jquery plugins used as part of GridView like `EditableColumn` are auto initialized
> 
> You can try to render dynamic content via PJAX in the same container and when you trigger `pjax:reload` via javascript the krajee plugins rendered inside will auto initialize.

Ok let me try that out, thank you for your suggestions and directions. Appreciate it.

**Comment by SplendornetTech** [comment]
> The yii2-grid extension already includes two properties in the `GridView` class i.e. `pjax` and `pjaxSettings` . Check docs.
> 
> If `pjax` is set to `true` - the extension wraps the grid in a pjax container with identifier based on `pjaxSettings` and the default activities like `pagination` and `filtering` are done via PJAX rendered content. In that case the jquery plugins used as part of GridView like `EditableColumn` are auto initialized
> 
> You can try to render dynamic content via PJAX in the same container and when you trigger `pjax:reload` via javascript the krajee plugins rendered inside will auto initialize.

I could move ahead a little based on your suggestion, here is the code I added in the event handler of the infinite scroll, and added below code just before it renders the new lines, so below code is for each row
$(".kv-editable-link").each(function(i) {
                        var class_string = $(this).parent().attr("class").split(" ");
                        var editable_class=class_string[0];
//set options again
                        window.editable_class = {"valueIfNull":"not set","asPopover":true,"placement":"left","target":".kv-editable-link","displayValueConfig":[],"ajaxSettings":[],"showAjaxErrors":true,"submitOnEnter":true,"selectAllOnEdit":true,"encodeOutput":true,"closeOnBlur":false,"validationDelay":500,"resetDelay":200,"animationDelay":300};
                        initEditablePopover($(this).attr("id"));                        
                        $("#oatype-"+i+"-delivery_date-cont").editable(editable_class);
}

Now I am getting below error

editable.js:367 Uncaught TypeError: Cannot read property 'apply' of undefined
    at HTMLDivElement.<anonymous> (editable.js:367)
    at Function.each (jquery.js:657)
    at init.each (jquery.js:266)
    at init.$.fn.editable (editable.js:360)

Can you please guide me what I am doing wrong and how it should be done? As you warned earlier it does not look like to be straightforward :-) So requesting your help.

Regards
Aditya

**Comment by SplendornetTech** [comment]
Finally could achieve what was required. Here is the reference for whoever wants to have similar solution

/**
    * Reinitialize the editable column so that the events are reattached to it again
    */
    function reInitializeEditableColumn(){
        // init editable column
        $(".kv-editable-link").each(function(i) {
            var currName = $(this).parent().attr("id");
            var currCapName="";
            if(currName.indexOf("oatype") == 0) {
                currName="oatype";
                currCapName="OaType";
            } else {
                currName="tempoatype";
                currCapName="TempOaType";
            }
            $(this).parent().attr("id",currName + "-"+i+"-delivery_date-cont");
            $(this).parent().find(".kv-editable-popover").attr("id",currName + "-"+i+"-delivery_date-popover");
            $(this).parent().find(".kv-editable-popover").find(".kv-editable-form").find("input[name=\'editableIndex\']").val(i);
            $(this).parent().find(".kv-editable-popover").find(".kv-editable-form").find(".kv-editable-parent").removeClass("field-"+currName+"-0-delivery_date").addClass("field-"+currName+"-"+i+"-delivery_date");
            $(this).parent().find(".kv-editable-popover").find(".kv-editable-form").find(".kv-editable-parent").find("#"+currName+"-0-delivery_date-kvdate").attr("id",currName+"-"+i+"-delivery_date-kvdate");
            $(this).parent().find(".kv-editable-popover").find(".kv-editable-form").find(".kv-editable-parent").find("#"+currName+"-0-delivery_date").attr("id",currName+"-"+i+"-delivery_date");
            $(this).parent().find(".kv-editable-popover").find(".kv-editable-form").find(".kv-editable-parent").find("#"+currName+"-"+i+"-delivery_date").attr("name",currCapName+"["+i+"][delivery_date]");
            $(this).parent().find(".kv-editable-popover").find(".kv-editable-form").find(".kv-editable-parent").find("#"+currName+"-"+i+"-delivery_date").attr("data-datepicker-source",currName+"-"+i+"-delivery_date-kvdate");
            $(this).attr("id",currName + "-"+i+"-delivery_date-targ");
            $(this).attr("data-target","#" + currName + "-"+i+"-delivery_date-popover");

            $("#"+currName + "-"+i+"-delivery_date-cont").editable("destroy").editable("create");//inite the event
            initEditablePopover($(this).attr("id"));                        
        });
    }

my element id value is tempoa-0-delivery_date so everything is related to it. This solution can be further improved to bring in speed and can be made it more generic to handle any id.

Hope it helps.

**Comment by SplendornetTech** [comment]
And call it as given below

'pager' => [
                'class' => \kop\y2sp\ScrollPager::className(),
                'container' => '.grid-view tbody',
                'item' => 'tr',
                'paginationSelector' => '.grid-view .pagination',
                'triggerTemplate' => '<tr class="ias-trigger"><td colspan="100%" style="text-align: left"><a style="cursor: pointer">{text}</a></td></tr>',
                'triggerOffset'=>$dataProvider->totalCount/$dataProvider->pagination->pageSize,
                'eventOnLoaded' => 'updateSummary',
                'eventOnRendered' => 'function() {
                    showColumns();
                    reInitializeEditableColumn()',
            ],
