### ISSUE TITLE
Problem in editable popup on mobile

### ISSUE THREAD

**Issue by abdil1234** [kartik-v/yii2-editable#204]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/31970269/94901699-3dfb2300-04c1-11eb-943b-9d6c5f0e073f.gif)

<img width="442" alt="Screen Shot 2020-10-02 at 15 19 27" src="https://user-images.githubusercontent.com/31970269/94903032-5bc98780-04c3-11eb-8120-35022bca4ee8.png">

i use latest version yii2 editable  and faced this error , how can i fix this issue? thanks

**Comment by kartik-v** [comment]
Yes this seems to be an issue only if you use TEXT INPUTS inside the Editable MODAL DIALOG Popup - but works fine for DROPDOWN LISTS and DATE PICKERS etc.

This needs to be checked when I have time. But you can use this as a workaround - set the Editable `asPopover` property to `false` this will render the editable content inline and not use a modal dialog popup.

**Comment by lbphp** [comment]
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/31970269/94901699-3dfb2300-04c1-11eb-943b-9d6c5f0e073f.gif)
> 
> <img alt="Screen Shot 2020-10-02 at 15 19 27" width="442" src="https://user-images.githubusercontent.com/31970269/94903032-5bc98780-04c3-11eb-8120-35022bca4ee8.png">
> 
> i use latest version yii2 editable and faced this error , how can i fix this issue? thanks
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/93458433-problem-in-editable-popup-on-mobile?utm_campaign=plugin&utm_content=tracker%2F4191889&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F4191889&utm_medium=issues&utm_source=github).

Are you putting yii2 editable inside a GridView? 
I have the same problem when it is inside a GridView, even the inline version
