### ISSUE TITLE
Popover editable always shown

### ISSUE THREAD

**Issue by tsanchev** [kartik-v/yii2-editable#205]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-editable.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/editable).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

composer.json
    
     ...
    "kartik-v/yii2-editable": "@dev"
     ...

in params.php as sugested in this issue https://github.com/kartik-v/yii2-editable/issues/191 :

    ....
    'bsVersion' => '4.x',
    'bsDependencyEnabled' => true,

in view file:

    <?= GridView::widget([
        ...
        'columns' => [
            ...
            [
                'class'=>'kartik\grid\EditableColumn',
                'attribute' => 'translation',
            ],
            ...
        ],
    ]); ?>

## Expected behavior and actual behavior

When the page loads i see this stacked popovers for all editable attributes in the grid view

![image](https://user-images.githubusercontent.com/8882098/99971695-36137d00-2da6-11eb-814a-40c7df1df1a7.png)

when i click to trigger the popover it is show in the proper place: 

![image](https://user-images.githubusercontent.com/8882098/99972704-89d29600-2da7-11eb-969d-c9e27052573c.png)

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-editable version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/editable)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-editable without other plugins.

**Comment by kartik-v** [comment]
By default the popover is set to be hidden on init as seen in the [bootstrap-popover-x CSS style](https://github.com/kartik-v/bootstrap-popover-x/blob/master/css/bootstrap-popover-x.css#L12)... due to some reason this is getting shown on init based on your PopoverX or Editable Settings... you can set the following CSS on your view / view layout file to avoid this ... but would recommend if you can check and let know what the settings are to find when this happens.

```
.popover-x { 
   display: none;
}
```

**Comment by uzkurama** [comment]
> By default the popover is set to be hidden on init as seen in the [bootstrap-popover-x CSS style](https://github.com/kartik-v/bootstrap-popover-x/blob/master/css/bootstrap-popover-x.css#L12). Check if you have updated release of the POPOVER-X plugin dependency. Else you need to check if due to some reason this CSS is getting overridden on init based on your PopoverX or Editable Settings. In that case, you can set the following CSS on your view / view layout file to avoid this ... but would recommend if you can check and let know what the settings are to find when this happens.
> 
> ```
> .popover-x { 
>    display: none;
> }
> ```

thanks, Kartik, for the future, If somebody uses AdminLTE3, u should know, in adminlte.css (or .min) there is one .popover class, comment or delete it to fix it.

**Comment by ilbassa** [comment]
Hi, we use AdminLTE3, but if we insert 
```
.popover-x{
    display:none !Important;
}
```
in our custom.css the popover doesn't show anymore after clicking on the data.
How we can fix this?

**Comment by DeveloperdotAbuzar** [comment]
Brothers,

if you are using Hail812 AdminLTE3 extension, it has prerquisite almasaeed2010.
to resolve this issue, go to:
     vendor\almasaeed2010\adminlte\dist\css\adminlte.min.css
Look for the css class ".popover" and remove this "display:block" in this class.

**Comment by DeveloperdotAbuzar** [comment]
> 

Great Job Kartik, 
Just want to let you know.

Brothers,

If someone is using Hail812 AdminLTE3 extension, it has prerequisite almasaeed2010.
to resolve this issue, go to:
     vendor\almasaeed2010\adminlte\dist\css\adminlte.min.css
Look for the css class ".popover" and remove this "display:block" in this class.

**Comment by Erebril** [comment]
This work for me

`<style>
    .popover {
        display:none;
    }
</style>`

paste this at the start of you view file. Not the most elegant thing but work for me on a single view
