### ISSUE TITLE
Android Virtual Keyboard disappearing when yii2-editable is inside a kartik's GridView

### ISSUE THREAD

**Issue by lbphp** [kartik-v/yii2-editable#207]
## Steps to reproduce the issue

1. put a column with 'class' => 'kartik\grid\EditableColumn', inside a kartik\grid\GridView 
  with 'editableOptions' => [
                'asPopover' => false,
                'inputType'=>\kartik\editable\Editable::INPUT_SPIN, or 'inputType'=>\kartik\editable\Editable::INPUT_TEXT,
]
2. try also with  'asPopover' => true,

## Expected behavior and actual behavior
When you touch the input to write a value on Android, the virtual keyboard disappears as if the input lost the focus.
If you have an Editable widget standalone (not as a GridView column), it works. The keyboard disappears only when the widget is inside a GridView.

One difference i have noticed between the two cases is: the input has "static" position in the standalone Editable widget, but "relative" if inside a GridView.
I then tried to force "position: static !important" via css, to no avail.

## Environment
dev

#### Browsers
Google Chrome

#### Operating System
Mobile Android

- jQuery version:
$.fn.jquery
"3.4.1"

- yii2-editable version:
{
    "name": "kartik-v/yii2-editable",
    "description": "An enhanced editable widget for Yii 2.0 that allows easy editing of displayed data with numerous configuration possibilities.",
    "keywords": ["bootstrap", "editable", "input", "widget", "popover-x", "popover", "jquery"],
    "homepage": "https://github.com/kartik-v/yii2-editable",
    "type": "yii2-extension",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Kartik Visweswaran",
            "email": "kartikv2@gmail.com",
            "homepage": "http://www.krajee.com/"
        }
    ],
    "require": {
        "kartik-v/yii2-widget-activeform": ">=1.5.7",
        "kartik-v/yii2-popover-x": "~1.3"
    },
    "autoload": {
        "psr-4": {
            "kartik\\editable\\": "src"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.7.x-dev"
        }
    }
}

**Comment by lbphp** [comment]
It seems that the responsiveWrap=true option of the GridView did the trick!
I don't know why exactly

**Comment by drew1two** [comment]
I have the same issue but responsiveWrap=true as GridView option didn't help.

Editable version:- 1.7.9
bootsrtap-popover-x version:- 1.4.7

`echo Gridview::widget([
            'dataProvider' => $providerProfileFees,
            'pjax' => true,
            'responsiveWrap'=>true,
            ...
`
`
            [
                'class'=>'kartik\grid\EditableColumn',
                'attribute'=>'date_paid',
                'label' => 'Last Paid',
                'format' => 'html',
                'width' => '25%',
                'refreshGrid' => true,
                'editableOptions' => function ($model, $key, $index)
                {
                    return
                    [
                        'inputType' => Editable::INPUT_WIDGET,
                        'widgetClass'=> 'kartik\datecontrol\DateControl',
                        'formOptions' => ['action' => ['/user/receive-payment']],
                        'resetButton' => ['style'=>'display:none;'],
                        'asPopover' => true,
                        'placement' => 'left',
                        'afterInput' => function ($form, $widget) use ($model, $index) {
                            $return = $form->field($model, "[$index]id")->hiddenInput()->label(false);
                            $return = $return . $form->field($model, "[$index]fee_amount", ['options' => []])->textInput(['value' => '', 'required' => true])->label('Amount');
                            return $return;
                        },
                        'options' => [
                            'type'=>\kartik\datecontrol\DateControl::FORMAT_DATE,
                            'ajaxConversion'=>true,
                            'pluginOptions' => [
                                'contentOptions' => function ($model, $key, $index, $column) {
                                    $nowDateFormatted = Yii::$app->formatter->asDate('now','medium');
                                    if (!empty($model->date_due)) {
                                        $dateDueFormatted = Yii::$app->formatter->asDate($model->date_due,'medium');
                                        if ($dateDueFormatted > $nowDateFormatted) {
                                            return ['style' => 'color:green;'];
                                        } else {
                                            return ['style' => 'color:red;'];
                                        }
                                    }
                                }
                            ]
                        ]
                    ];
                }
...`

**Comment by kartik-v** [comment]
This is fixed via [this commit](https://github.com/kartik-v/bootstrap-popover-x/commit/2362dae35e06189e9266cf6a364d37e5e80f7614) as mentioned in kartik-v/bootstrap-popover-x#46
