### ISSUE TITLE
On the demo webpage, page moves every time an editable widget is clicked 

### ISSUE THREAD

**Issue by newadventure079** [kartik-v/yii2-editable#218]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-editable.
- [x] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/editable).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
Go to the demo page https://demos.krajee.com/editable and click on a widget
The webpage will move down with each click

![Screenflick Movie](https://user-images.githubusercontent.com/84156407/184999064-58cf7f9a-caf9-48be-95d7-466809ba8316.gif)

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-editable version:

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/editable)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-editable without other plugins.

**Comment by kartik-v** [comment]
This has been fixed with the [updated version 1.5.2](https://github.com/kartik-v/bootstrap-popover-x/releases/tag/v1.5.2) of the bootstrap-popover-x plugin. Update your packages via composer to get the latest code.
