### ISSUE TITLE
Before Submit

### ISSUE THREAD

**Issue by Heddy147** [kartik-v/yii2-editable#26]
Hello,

I want to change the value of the input before "submitting" the form.

My situation:
I create a gridview. There I have a column which is formattet like this: "key1"=>"value1","key2"=>"value2" (hstore in PostgreSQL).
The output in the gridview is correct. I want to edit this value like an array:
| INPUT FOR KEY | = | INPUT FOR VALUE |
...
I add rows for a new key-value pair with javascript.
Now I want to format it to the syntax of the hstore.

Is there a way to trigger a "beforeSubmit"-method for formatting the "new" inputs?

Thanks and best regards from Germany,

Heddy147

**Comment by kartik-v** [comment]
Use `editableSubmit` event.
