### ISSUE TITLE
Several instances of same model and attribute

### ISSUE THREAD

**Issue by gael-wogenstahl** [kartik-v/yii2-editable#36]
Hi Kartik,

I was wondering how I can display several Editable widgets for several instances of the same model and same attribute. I tried it but since the IDs of the different parts of the widget are the same (same model name and same attribute), the popover that shows is always the one from the first instance of all my models.
I tried to set the ID myself using the options but that doesn't work. any idea ?

Also is there a way to display the editable button as disabled like you can do with fields and other bootstrap buttons ? I added `['disabled' => true]` to the `editableButtonOptions` which actually prevent the user from using the button but doesn't display a nice cursor like disabled fields.
Also the button turns square instead of round as it seems that setting the `editableButtonOptions` property remove the `btn`, `btn-sm` and `btn-default` CSS classes from the button.

Thanks for your help with those questions.

**Comment by kartik-v** [comment]
Take an inspiration from the yii2-grid EditableColumn... it has the editable widget implemented for the same model and attribute (for all rows in the column). You need to setup the attribute name similarly... in array format.

On the disabled property CSS styling - will check and get back when I get time.

**Comment by gael-wogenstahl** [comment]
Thanks that worked :+1: 

Let me know about the styling when you can.

**Comment by kartik-v** [comment]
Refer #40 for the disabled button styling.

**Comment by cimmmy** [comment]
Hi kartik,
I would need the key-feature in a ListView.
Is it possible to use?

**Comment by dawidof** [comment]
Get the same issue with multiple elements(working only first), but couldn't resolve.
Here is my code
```php
foreach ($integrations as $integration) {
      echo Editable::widget([
            'attribute'=>'campaign_id',
            'model' => $integration,
            'asPopover' => false,
            'format' => Editable::FORMAT_BUTTON,
            'inputType' => Editable::INPUT_DROPDOWN_LIST,
            'data' => (new common\models\Campaign())->getSource(),
            'options' => ['class'=>'form-control', 'prompt'=>'Select campaign...'],
            'editableValueOptions'=>['class'=>'text-danger'],
            'formOptions' => ['action' => '/dashboard/integration/' . $integration['id']],
            'valueIfNull' => '(not set)',
            'displayValue' => (isset($integration->campaign) ? $integration->campaign->title : null),
            // 'editableButtonOptions' => ['disabled' => true]
      ]);
}

```

Could you help?
