### ISSUE TITLE
"valueIfNull" option is not working

### ISSUE THREAD

**Issue by alexweb** [kartik-v/yii2-editable#39]
"valueIfNull" option is not working

**Comment by alexweb** [comment]
It still inserts "<em>(not set)</em>" text insted of the value defined in "valueIfNull" parameter (in editableColumn)

**Comment by kartik-v** [comment]
You must record the issue in the correct repo... note that `EditableColumn` is different than this extension and is part of yii2-grid. 

Anyway this will be fixed via kartik-v/yii2-grid#237.

**Comment by alexweb** [comment]
Thanks
