### ISSUE TITLE
TypeError: this.$dialog is undefined

### ISSUE THREAD

**Issue by iyoba** [kartik-v/yii2-editable#42]
Hi,
Before this issue I use v3.3.2 it work perfect,
after update to v3.3.4 I found this error

TypeError: this.$dialog is undefined
this.$dialog.on('mousedown.dismiss.bs.modal', function () {
bootstrap.js (line 972, col 4)

TypeError: this.$dialog is undefined
this.$dialog.off('mousedown.dismiss.bs.modal')
bootstrap.js (line 1035, col 4)

I use Yii2 framework with this widget https://github.com/kartik-v/yii2-editable

**Comment by kartik-v** [comment]
Duplicate to kartik-v/yii2-popover-x#6 and resolved via the same issue.
