### ISSUE TITLE
Editable is not POST to Active form action

### ISSUE THREAD

**Issue by iyoba** [kartik-v/yii2-editable#43]
My Code in "/manage/shop/index"
            <?php $form = ActiveForm::begin([
	            'id'          => 'shop-form',
	            'action' => ['/manage/shop/update'],
	            'options'     => ['class' => 'form-horizontal'],
	            'fieldConfig' => [
	                'template'     => "{label}\n<div class=\"col-lg-9\">{input}</div>\n<div class=\"col-sm-offset-3 col-lg-9\">{error}\n{hint}</div>",
	                'labelOptions' => ['class' => 'col-lg-3 control-label'],
	            ],
	            'method'=>'post',
	            'enableAjaxValidation'   => true,
	            'enableClientValidation' => false,
	        ]); ?>
				<?php
					echo Editable::widget([
					    'name'=>'name',
					    'value' => $model->name,
					    'header' => 'Name',
					    'size'=>'md',
					    'options' => ['class'=>'form-control', 'placeholder'=>'Enter shop name...'],
					]);
				?>
			<?php ActiveForm::end(); ?>

When i click Apply, It's request GET to url  /manage/shop/index

Also I read you demo page and document many time.

**Comment by kartik-v** [comment]
Your code will not work and is incorrect - since its causing an INVALID HTML due to nested forms and will be treated as invalid HTML by browsers. 

Note that Editable widget generates its own FORM tag and inputs inside - so you should NEVER embed a editable widget inside another form.
