### ISSUE TITLE
How to show multiple validate message to each field following ActiveForm::validate()

### ISSUE THREAD

**Issue by iyoba** [kartik-v/yii2-editable#45]
I have question
I use this code
	<?php
				echo '<label>Address</label><br>';
				$editable = Editable::begin([
				    'model'=>$model,
				    'attribute'=>'address',
				    'size'=>'md',
				    'displayValue' => '15th Main, OK, 10322',
				    'options'=>['placeholder'=>'Enter address...']
				]);
				$form = $editable->getForm();
				echo Html::hiddenInput('kv-complex', '1');
				$editable->afterInput =
				    $form->field($model, 'province_id')->widget(\kartik\widgets\Select2::classname(), [
				        'data'=>ArrayHelper::map($modelProvince, 'province_id', 'province_name'),
				        'options'=>['placeholder'=>'Enter province...'],
				        'pluginOptions'=>['allowClear'=>true]
				    ]) . "\n" .
				    $form->field($model, 'zipcode')->textInput(['placeholder'=>'Enter zip code...']);
				Editable::end();
			?>

When I submit data, in Controller I validate data by use below function.
ActiveForm::validate($model)

and return validated data as below
{"usershop-address":["Address cannot be blank."],"usershop-province_id":["Province cannot be blank."],"usershop-zipcode":["Zipcode cannot be blank."]}

Question is, How to show each error message to each input field?

Thanks,

**Comment by kartik-v** [comment]
You should use ideally yii model validation rules for each attribute for the above... and not use Controller to validate this. Read about yii model validation rules in yii guides where you can set `required` property for each attribute to achieve what you want.
