### ISSUE TITLE
high reset button

### ISSUE THREAD

**Issue by zhjyii** [kartik-v/yii2-editable#46]
A question: is it possible to hide the reset button?
Tried 'resetButton'=>null but a not styled reset button is till shown.
Sometimes a reset button doesn't make sense and will only confuse users, would be nice to diable it.

**Comment by kartik-v** [comment]
Please read the [documentation and settings for Editable widget](http://demos.krajee.com/editable#settings) as most of these are already answered there.

- You can set `resetButton => ['class'=>'hide']` to hide the resetButton
- You can set `showButtons` to `false` to hide both buttons
- The `footer` property defaults to `{buttons}` which replaces it with submit & reset buttons.. you can append or change your own buttons if needed.
