### ISSUE TITLE
Conflit with jquery-ui

### ISSUE THREAD

**Issue by levanlau** [kartik-v/yii2-editable#50]
Hi !
- <b>Before when using jquery-ui:</b>
![editable-datepicker-error](https://cloud.githubusercontent.com/assets/3320397/6767864/6d7af1d4-d07c-11e4-8dad-a6b7f9877c99.png)
- <b>After when using jquery-ui, there is an error follwing:</b>
![editable-datepicker](https://cloud.githubusercontent.com/assets/3320397/6767866/8a4be1ce-d07c-11e4-9eab-347affcab43d.png)
<b>=>This mean that there is a clash between jquery of editable and jquery-ui.
But, i don't want to give up jquery-ui.js in my project.
Is there any ways help me this ? thanks. :)</b>
Lau.

**Comment by kartik-v** [comment]
This has actually got nothing to do with the editable widget.

Its more to do with the DatePicker widget. Both JUI datepicker and bootstrap-datepicker plugin use the same namespace `$.fn.datepicker`

Refer [my comment here](https://github.com/kartik-v/yii2-widgets/issues/158#issuecomment-56619745) and the source issue raised on the [bootstrap-datepicker plugin project page](https://github.com/eternicode/bootstrap-datepicker/issues/1100).

There needs to be a change to datepicker to use a noconflict method.

**Comment by levanlau** [comment]
Hi,
At #50 issue, i use 'inputType'=>Editable::INPUT_DATE in widget Editable attribute, but if i use 'inputType'=>Editable::INPUT_DATETIME, nothing happen error.
So, i think the issue is  'inputType'=>Editable::INPUT_DATE, not jquery-ui.
I don't know i think that is ok ?

**Comment by kartik-v** [comment]
Did you read my comment before? I had mentioned the same thing... Editable::INPUT_DATE uses `bootstrap-datepicker` plugin and the error is due to conflict of using the same jquery function `$.fn.datepicker` in both bootstrap-datepicker and juidatepicker.

**Comment by kartik-v** [comment]
Ok I closed this with fixes to yii2-widget-datepicker in v1.3.3 and by extending the bootstrap-datepicker plugin. 

Resolved via kartik-v/yii2-widget-datepicker#27.

**Comment by levanlau** [comment]
Ok, thanks.:)
