### ISSUE TITLE
Error does not reset when using PasswordInput widget

### ISSUE THREAD

**Issue by gael-wogenstahl** [kartik-v/yii2-editable#56]
Hi Kartik,

I'm using the `yii2-editable` widget with the input type `'widget'` and the `yii2-password` widget to allow my users to change their password while controlling the strength.

It works great when the user input is valid. However when the password doesn't validate, the error message is displayed correctly but it seems it's not reset when another value is typed in the input. Even if the user type a valid password, the previous error is still displayed and the `yii2-editable` widget doesn't close.
I check the AJAX response in that case and the JSON is correct : `output` contains the text I want to display instead of password and `message` is empty.
If I reset the `yii2-editable` form with the button, the error goes away and it works again with a valid password.

Do you have an idea why it's behaving that way ? Am I doing something wrong ? Maybe the was the `yii2-password` widget works doesn't allow the Editable widget to reset the error ?

Thank you for your help solving that issue !

**Comment by kartik-v** [comment]
Will fix with release 1.7.3

**Comment by kartik-v** [comment]
Check with the updated release v1.7.3.

**Comment by gael-wogenstahl** [comment]
Works like a charm ! You rock ! :)
