### ISSUE TITLE
Problem using model & attribute

### ISSUE THREAD

**Issue by tsvetann** [kartik-v/yii2-editable#66]
I have multiple comments in one page. I would like to make each one inline editable. But when I use model & attribute only the first comment gets inline editable, the rest don't work (meaning nothing happens when I click on them).
Code:
```php
echo Editable::widget([
                                'model' => $comment,
                                'attribute' => 'comment',
                                'asPopover' => false,
                                'value' => $comment->comment,
                                'format' => Editable::FORMAT_BUTTON,
                                'header' => 'Name',
                                'size'=>'md',
                                'inputType' => Editable::INPUT_TEXTAREA,
                                'options' => ['class'=>'form-control', 'placeholder'=>'Edit comment...']
                            ]);
```

If I use 'name' instead of model & attribute they work but then I cannot validate against model!

**Comment by kartik-v** [comment]
Been asked and answered before in other places as well.. your use case will wrongly render duplicate HTML identifiers - which is not good for both your HTML markup output as well all jquery plugins which initialize using HTML element id and hence will be broken.

All jquery based plugins like EDITABLE need a unique HTML ID to work... you must set a unique id

```php
echo Editable::widget([
    'model'=>$comment,
    'attribute'=>'comment',
    'options'=>['id'=>'comment-unique-id-1'] // must be unique for EVERY editable widget
]);
```
