### ISSUE TITLE
Rendering INPUT_SWITCH attribute for more than 1 model

### ISSUE THREAD

**Issue by w00ppay** [kartik-v/yii2-editable#67]
I render attribute `is_active` of multiple `core` model objects on a single view. I have generated attribute `id` in `options`:
```php
    Editable::widget([
         'model'=> $core, 
         'attribute' => 'is_active',
         'inputType' => Editable::INPUT_SWITCH,
         'size' => kartik\popover\PopoverX::SIZE_MEDIUM,
         'displayValueConfig' => [
                 0 => '<span class="label label-danger">Нет</span>',
                 1 => '<span class="label label-success">Да</span>'
         ],
         'options' => ['id' => $core->id.'-is_active'],
         'formOptions' => [
             'action' => '/core/update?id='.$core->id,
        ]])
```
The problem is that the popup switch for the attribute renders only for very first object on page. Others have just simple checkbox in popup. I found that every tag `input` with attribute `data-krajee-bootstrapswitch` have same `id` called `core-is_active`. Can I set the `id` attribute within widget config array?

**Comment by kartik-v** [comment]
Yes you may read the [documentation for Editable widget settings](http://demos.krajee.com/editable#settings).

You can set the id for the widget in `Editable::options['options']['id']`.
