### ISSUE TITLE
Button class missing when custom submitButton, resetButton icon

### ISSUE THREAD

**Issue by yoyhosoft** [kartik-v/yii2-editable#71]
echo \kartik\editable\Editable::widget([
           ......
            'format' => Editable::FORMAT_BUTTON,
            'inputType'=> Editable::INPUT_TEXT,
            'submitButton' => [
                'icon' => '<i class="glyphicon glyphicon-ok"></i>',
                'label' => 'Save'
            ],
            'resetButton' => [
                'icon' => '<i class="glyphicon glyphicon-remove"></i>',
                'label' => 'Cancel'
            ]
        ]);

I config like this, when render submitButton and resetButton not append class for button
(like 'btn btn-sm btn-default')

<button type="button" class="kv-editable-reset">
    <i class="glyphicon glyphicon-remove"></i> Cancel
</button>
<button type="button" class="kv-editable-submit">
    <i class="glyphicon glyphicon-ok"></i> Save
</button>

**Comment by kartik-v** [comment]
Yes you need to add your own CSS class for the buttons if you are overriding the default styles. This is to allow people to use their own non-bootstrap CSS if needed.
