### ISSUE TITLE
DepDrop field missing on form submission

### ISSUE THREAD

**Issue by rlmckenney** [kartik-v/yii2-editable#74]
I am attempting to use the DepDrop widget as one of several address related fields in an Editable widget.

When using DepDrop either as the primary field or an additional field (I have tried it both ways), the DepDrop field is excluded from the post data sent by ajax on submit. The serialize function just doesn't see it.

For more details see the issue opened in [kartik-v/yii2-widgets] (https://github.com/kartik-v/yii2-widgets/issues/256)

**Comment by kartik-v** [comment]
You may need to debug and check your Controller action output and JSON. Also check the Editable response for various logical conditions in your code.

Have updated an example of Editable with Depdrop in the usage examples in the last section for both [popover example](http://demos.krajee.com/editable#usage-popover) and [inline example](http://demos.krajee.com/editable#usage-popover).
