### ISSUE TITLE
EditableColumn with Input, Input Popup does not display default value using ArrayDataProvider

### ISSUE THREAD

**Issue by blackcuttle** [kartik-v/yii2-editable#75]
Is there any solution? maybe with 
'editableOptions' => ['name' => 'quantity', 'value' => ??],

I guess it's not a good idia to edit, yii2-Editable\Editable.php, but I couldn't find another way to fix it..

        $value = $this->hasModel() ? Html::getAttributeValue($this->model, $this->attribute) : $this->value;
        if ($value === null && !empty($this->valueIfNull)) {
            $value = $this->valueIfNull;
        }
        if (!isset($this->displayValue)) {
            $this->displayValue = $value;
        }
       // added:
        if (!isset($this->value)) {
            $this->value = $this->displayValue;
        }

**Comment by kartik-v** [comment]
No it is not recommended. You can try to set the input value directly via `options['value']` within the form input options for your use case.

**Comment by rendragnet** [comment]
Just for anyone else who comes across this, the solution is to use 'value' => $model['value'].  By default it tries to use $model->value which does not work, as it's an array, not an object.

**Comment by lbphp** [comment]
@rendragnet Have you tested it? Doesn't work for me. 
I have a GridView where the initial values are correctly displayed, but the input fields in the Popovers are empty

```
[
            'class' => 'kartik\grid\EditableColumn',
            'attribute' => 'comments',
            'header' => 'Comments',
            'value'=>function ($model, $key, $index, $widget){
                    // $model comes from an ArrayDataProvider of the GridView widget
                    return $model['comments'];
                },
            'editableOptions' => function ($model, $key, $index) use($ajaxAction){
                                    return [
                                        'header' =>'the comment',
                                        'size'=>'md',
                                        'inputType'=>\kartik\editable\Editable::INPUT_TEXT,
                                        'name'=>'comments',
                                        'formOptions'=>['action' => [$ajaxAction] ],
                                        'placement'=>'bottom',
                                    ];
                                }
        ],
```
