### ISSUE TITLE
renderAjax on reopen of modal

### ISSUE THREAD

**Issue by fennellgb23** [kartik-v/yii2-editable#77]
I'm having a problem with kartik\editable\Editable.  Here are the steps to produce.

1. Click on item to open a modal with an kartik\editable\Editable in it. (body of modal is rendered with renderAjax from a jquery $.post().done() )
2. Use editable and change data (works perfectly).
3. Close modal
4. Reopen modal by doing same click on item (no refresh of page)
5. kartik\editable\Editable does not work

NOTE: If I refresh page and start from step 1 get same results
NOTE2: Can do same steps with other components (i.e. datepicker) and not have same problem on a reopen of the modal.

**Comment by kartik-v** [comment]
You need to check your app code whenever you are overwriting markup via AJAX as that typically break the jQuery plugins initialized on elements that are overwritten. 

Ensure the Editable plugin is reinitialized after the content is rendered. Also you may want to try the new `destroy` method as described in the issues #87 and #100.

**Comment by jotapeserra** [comment]
@kartik-v i cant get that done right... do you have an example of this please?
