### ISSUE TITLE
Image field not comming to controller

### ISSUE THREAD

**Issue by thiagomoraesp** [kartik-v/yii2-editable#79]
Here is my code

echo Editable::widget([
    'model' => $model,
    'attribute' => 'arquivo_imagem_de_perfil',
    'type' => 'primary',
    'size' => 'lg',

    'format' => Editable::FORMAT_BUTTON,
    'inputType' => Editable::INPUT_FILE,
    'asPopover' => true,
    'editableButtonOptions' => ['label' => '<i class="glyphicon glyphicon-camera pull-right"></i>'],
    'editableValueOptions' => ['class' => 'texto-editavel inline'],
    'formOptions' => [
        'action' => 'index.php?r=perfil/update-dinamico&id=' . $this->params['modelo_perfil']->id
    ]
    ]);

It generates a file upload field, but i can't get it in the controller, it don't come on _POST or _FILES :(

**Comment by kartik-v** [comment]
This is not supported currently - because the Editable sends the form via jQuery `form.serialize` method which does not send blobs or files - but will send all other inputs.
