### ISSUE TITLE
Editable within AJAX-loaded tab results in popover below surrounding div

### ISSUE THREAD

**Issue by matthewdaize** [kartik-v/yii2-editable#81]
Using the editable widget (in popover mode) within an AJAX rendered tab works. However when clicking on the editable button to show the popover, it is hidden behind the div of the tab it is rendered in.

I have tried mucking with z-index without success.

**Comment by kartik-v** [comment]
Yes you need to try editing the CSS for your use case... alternatively you may try using the editable inline mode (instead of popover).
