### ISSUE TITLE
custom validation on editable field

### ISSUE THREAD

**Issue by GIGS1975** [kartik-v/yii2-editable#82]
Hi.
I appologize ahead, if this issue is not related with editable field,( maybe it is).
If a make a validation rule for two numbers like this:
['number1','comapre','comapreAttribute,'number2','type'=>'number','operator'=>'<','message'=>
'number1 must be less than number2']
This doesn't work. It throws the error message for any inserted value. It doesn't matter if the number1 is lower or higher than number2, the error gets showed.
But when i create a custom function like:
['number1','customFunc']
public function ($attribute,$params)
{
If ($this->number1 >= $this->number2)
{ $this->addError($attribute, 'Number1 must be lower than number2!'; }
}
This works fine! Can you see where can be the problem please? 
I have tried some var_dump, and it seems that in first case, the compared value stays as it is in the database, and not gets the value beeing inserted. 

In controller i have:

 $searchModel = new MaxdaySearch();
 $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

if (Yii::$app->request->post('hasEditable')) {
        
		
        $id = Yii::$app->request->post('editableKey');
        $model = Maxday::findOne($id);
 		
 		
        
        $out = Json::encode(['output'=>'', 'message'=>'']);
 
 		
        $post = []; 
        
		
        $posted = current($_POST['Maxday']); 
        
        
        $post['Maxday'] = $posted;
			
			if ($model->load($post)) {
if (isset($posted['number1'])) 
 			{

$output = $model->stockfutureend;
$message = '';

			} 
if ($model->save())
{					
					$out = Json::encode(['output'=>$output, 'message'=>'']);
					echo $out;
				}
		
			else 
				{
							$message1 =$model->getFirstErrors();	
							$message = array_values($message1);
							$r = Json::encode(['result'=>0, 'message'=>$message[0]]);	
					   		echo $r;
				}
			 
            

} 

} 
       
        return;
    }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

Thanks

**Comment by kartik-v** [comment]
This is related to model validation rules supported by Yii and not related to this extension. You may study yii model validation and client validation rules in Yii docs for this.
