### ISSUE TITLE
Using v1.7.2, undefined is not a function elm.replace

### ISSUE THREAD

**Issue by zmoddynamics** [kartik-v/yii2-editable#86]
I receive this in console log after trying your extension. Any Idea what could be wrong. I'm using v1.7.2..
TypeError: undefined is not a function (evaluating 'elem.replace( rxhtmlTag, "<$1></$2>" )')

**Comment by kartik-v** [comment]
Not clear as your problem cannot be reproduced. Recommend you upgrade to the latest stable release which is currently v1.7.3

**Comment by zmoddynamics** [comment]
You are correct. It wasn¹t problem with v1.7.2 but that I had:

<?php ActiveForm::begin(); ?>

echo Editable::widget([ 'model'=>$model->getUser()->one(),
'attribute'=>'username', 'header'=>'username', 'format' =>
Editable::FORMAT_BUTTON, 'size'=>'md', 'displayValue' =>
$model->getUser()->one()->username, 'valueIfNull' => '(not set)',
'options'=>['placeholder'=>'Change username...'], 'placement' =>'top',
'editableValueOptions'=>['class'=>empty($model->getUser()->one()->username)
? 'text-danger':''] ]);


<?php ActiveForm::end(); ?>

I did not realize that the widget created its own form and this was the
mistake. Thanks!


Warm Regards,
 
Clint Zeringue, Ph.D.
Scientific Programmer/Web Developer
Office: 832.945.5568 <file://localhost/tel/832.945.5568>
Cell: 657.201.9663 <tel:657.201.9663>
Skype: clint.zeringue
clint.zeringue@zmoddynamics.com


 
This email is intended only for the person to whom it is addressed and/or
otherwise authorized personnel. The information contained herein and
attached is confidential and the property of ZModDynamics LLC. If you are
not the intended recipient, please be advised that viewing this message and
any attachments, as well as copying, forwarding, printing, and disseminating
any information related to this email is prohibited, and that you should not
take any action based on the content of this email and/or its attachments.
If you received this message in error, please contact the sender and destroy
all copies of this email and any attachment. Please note that the views and
opinions expressed herein are solely those of the author and do not
necessarily reflect those of the company. While antivirus protection tools
have been employed, you should check this email and attachments for the
presence of viruses. No warranties or assurances are made in relation to the
safety and content of this email and attachments. ZModDynamics LLC accepts
no liability for any damage caused by any virus transmitted by or contained
in this email and attachments. No liability is accepted for any consequences
arising from this email.


 ZModDynamics LLC
28210 Emerald Creek Ln, Fulshear,TX 77441
Tel: 657.201.9663 <tel:657.201.9663>
zmoddynamics.com <http://www.zmoddynamics.com>
Facebook <https://www.facebook.com/zmoddynamics>  | LinkedIn
<http://www.linkedin.com/company/2973453>  | Twitter
<https://twitter.com/ZModDynamics>

From:  Kartik Visweswaran <notifications@github.com>
Reply-To:  kartik-v/yii2-editable
<reply+000eb5a5c9a092bd5228ecd5dbf45d013bb202f88661480992cf0000000111d9f93b9
2a169ce05e1a9bb@reply.github.com>
Date:  Wednesday, August 5, 2015 at 11:18 AM
To:  kartik-v/yii2-editable <yii2-editable@noreply.github.com>
Cc:  "Clint Zeringue,Ph.D." <Clint.Zeringue@ZModDynamics.com>
Subject:  Re: [yii2-editable] Using v1.7.2, undefined is not a function
elm.replace (#86)


Not clear as your problem cannot be reproduced. Recommend you upgrade to the
latest stable release which is currently v1.7.3


Reply to this email directly or view it on GitHub
<https://github.com/kartik-v/yii2-editable/issues/86#issuecomment-128056206>
.
