### ISSUE TITLE
Tag display value is not purified for xss attack

### ISSUE THREAD

**Issue by seerjun** [kartik-v/yii2-editable#89]
Hi kartik,

When I insert script as a tag value in editable, the value is not encoded or purified. Is there any way to prevent this attack?
![01](https://cloud.githubusercontent.com/assets/11764474/9400464/0ef4299c-47f4-11e5-9975-e0e70bb8908e.png)

![02](https://cloud.githubusercontent.com/assets/11764474/9400466/139986b8-47f4-11e5-859f-8e4acabee436.png)

**Comment by kartik-v** [comment]
Duplicate to #91 ... there is a new `encodeOutput` property which defaults to `true`.
