### ISSUE TITLE
 Editable content is not HTML encoded

### ISSUE THREAD

**Issue by nagyt234** [kartik-v/yii2-editable#91]
The editable content is not HTML encoded after saving, e.g. it is possible to disturb the page in the first demo on the [demo page](http://demos.krajee.com/editable#usage-inline) by entering "Kartik Vis</input><input>waran". How to solve this problem?

**Comment by kartik-v** [comment]
Yes can handle it in your controller action that processes the editable form submission by HTML.

But noting an enhancement for encoding in the plugin as well.
