### ISSUE TITLE
Editable select looks only for the option value and not text

### ISSUE THREAD

**Issue by stratoss** [kartik-v/yii2-editable#93]
It looks like when I have editable field in GridView, the plugin looks only for the option key. I'm using a function to display custom content. Example:

```
'data' => [
    1 => 'Active',
    4 => 'Disabled'
],
```

If I return 1 or 4 from the Ajax call, and try to re-edit that field, the select field is marking the correct option as selected, but if I return 'Active' or 'Disabled', always 'Active' is selected.

**Comment by kartik-v** [comment]
You kind of answered your own question. Yes you must pass the input value stored in the base attribute and not derived descriptions.

**Comment by stratoss** [comment]
That sounds okay, but the editable plugin is overwriting the content with the key. I have gridview column like:
```
'content' => function ($model) use ($column) {
    /* @var $model common\models\Users */
    switch($model['status']) {
        case 1:
            $statusText = 'Active';
            break;
        case 4:
            $statusText = 'Disabled';
            break;
        default:
            $statusText = '';
    }
    return $statusText;
}
```

I want to display a more human-readable status than a number. Am I doing it wrong?

**Comment by stratoss** [comment]
I just realized that even in the first iteration when the page is loaded, the proper option is not selected when editing, so if I rewrite the content with the function above the plugin is not recognizing it.
