### ISSUE TITLE
Input validation works only when input is out of focus

### ISSUE THREAD

**Issue by KirillRyzhkov** [kartik-v/yii2-editable#97]
I setup Editable column according to your tutorial and everything is working fine except for validation
For example, I have
<pre> [['country_id', 'country_population'], 'integer']</pre>
So when I open edit popover and write text string in there and press Apply the validation won't let to save into DB but the edit popover closes and the table displays submitted value but after page refresh it shows previous value because it did not save into DB.

But it is very interesting issue is that when I write text string into the input and hit out of the input so it is not focused validation actually works and red message displays under the input field [ Country Population must be an integer ] and Apply button won't let close the edit popover.

So, how to fix this problem? I think it is very confusing for the end user.

Main problem is that validation is not triggered when Submit button is pressed first time.

**Comment by kartik-v** [comment]
That is the default yii client validation behavior (either the `blur` or `change` event)
