### ISSUE TITLE
displayValueConfig does not accept glyphicons

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-editable#98]
I'm trying to replace my editable text by glyphicons using this configuration in a gridview:

        [   
            'attribute' => 'status',
            'class' => 'kartik\grid\EditableColumn',
            'editableOptions' => [
                'asPopover' => false,
                'inputType' => Editable::INPUT_DROPDOWN_LIST,
                'data' => ['pass','fail','waived','todo'],
                'displayValueConfig' => ['pass' => '<i class="glyphicon glyphicon-thumbs-up">',
                                         'fail' => '<i class="glyphicon glyphicon-thumbs-down">',
                                         'todo' => '<i class="glyphicon glyphicon-hourglass">',
                                         'waived' => '<i class="glyphicon glyphicon-flag">'],
            ],
        ],

I get all glyphicons 3 times, the first one is the clickable link, the other two are not.

**Comment by akorinek** [comment]
![snapshot1](https://cloud.githubusercontent.com/assets/1334533/11171508/e5addef6-8bbf-11e5-8933-3d1d4c3e75f9.png)

**Comment by kartik-v** [comment]
Your configuration is wrong - your display value config do not match the array keys for dropdown data. Check the [third example in the Editable Demo](http://demos.krajee.com/editable#usage-popover) which has your use case above configured.
