### ISSUE TITLE
Can't install with kartik base 1.7.8

### ISSUE THREAD

**Issue by KirillRyzhkov** [kartik-v/yii2-editable#99]
Hi,

I have problem updating Editable 1.7.2 to 1.7.3 . I have Kartik base - 1.7.8 and when I add
"kartik-v/yii2-editable": "*" or "kartik-v/yii2-editable": "@dev" . Composer says it has nothing to update and when I add "kartik-v/yii2-editable": "1.7.3" it gives error
<pre>
 Problem 1
    - Installation request for kartik-v/yii2-editable 1.7.3 -> satisfiable by kartik-v/yii2-editable[v1.7.3].
    - kartik-v/yii2-editable v1.7.3 requires kartik-v/yii2-krajee-base ~1.7 -> no matching package found.

</pre>

**Comment by kartik-v** [comment]
Cannot reproduce. Retry with the latest releases.

**Comment by Jimmea** [comment]
why i can't install package editable @kartik-v . Please help me .

**Comment by kartik-v** [comment]
You may need to debug the composer dependencies yourself for your app and see if its fine.

Try with `"kartik-v/yii2-editable": "*"` or `"kartik-v/yii2-editable": "@dev"` and check. 

You may follow this [web tip for resetting composer packages to an extent](http://webtips.krajee.com/composer-fails-update-vendor-packages/)
